#!/bin/sh

# Set up Homebrew

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# install the apps I use every day

brew install --cask firefox
brew install --cask visual-studio-code
brew install fastfetch
brew install byobu
brew install --cask spotify
brew install --cask dropbox
brew install --cask vlc
brew install --cask proton-drive
brew install --cask proton-vpn

# install the apps I use occasionally

brew install --cask gimp
brew install --cask inkscape
brew install --cask blender
brew install --cask krita
brew install --cask audacity
brew install --cask handbrake
brew install --cask calibre
brew install --cask slack
brew install --cask zoom
brew install --cask microsoft-teams
brew install --cask ungoogled-chromium
brew install --cask mactracker
brew install --cask qmk-toolbox
