#!/bin/sh

#  _   _ ____  ____    _  _____ _____    _    _     _     
# | | | |  _ \|  _ \  / \|_   _| ____|  / \  | |   | |    
# | | | | |_) | | | |/ _ \ | | |  _|   / _ \ | |   | |    
# | |_| |  __/| |_| / ___ \| | | |___ / ___ \| |___| |___ 
#  \___/|_|   |____/_/   \_\_| |_____/_/   \_\_____|_____|
#
# Runs a full local maintenance pass on macOS by applying system updates,
# updating Homebrew formulae, syncing keyboard keymaps from Dropbox into
# qmk_firmware when Dropbox is present, and updating Nix packages when Nix
# is installed.

# macOS updates

sudo softwareupdate -i -a

# App store updates

mas upgrade

#Homebrew updates

brew update
brew upgrade

# Sync QMK

if [ -d "/Applications/Dropbox.app" ] || [ -d "$HOME/Applications/Dropbox.app" ] || [ -d "$HOME/Dropbox" ]; then
	rsync -avz /Users/andy/Dropbox/Scripts/github/keyboards/planck/ /Users/andy/qmk_firmware/keyboards/planck/keymaps/teknostatik/
	rsync -avz /Users/andy/Dropbox/Scripts/github/keyboards/preonic/ /Users/andy/qmk_firmware/keyboards/preonic/keymaps/teknostatik/
	rsync -avz /Users/andy/Dropbox/Scripts/github/keyboards/corne/ /Users/andy/qmk_firmware/keyboards/crkbd/keymaps/teknostatik/
	rsync -avz /Users/andy/Dropbox/Scripts/github/keyboards/corne36/ /Users/andy/qmk_firmware/keyboards/crkbd/keymaps/teknostatik36/
	rsync -avz /Users/andy/Dropbox/Scripts/github/keyboards/HHKB/ /Users/andy/qmk_firmware/keyboards/hs60/v2/hhkb/keymaps/teknostatik/
	rsync -avz /Users/andy/Dropbox/Scripts/github/keyboards/gherkin/ /Users/andy/qmk_firmware/keyboards/40percentclub/gherkin/keymaps/teknostatik/
	rsync -avz /Users/andy/Dropbox/Scripts/github/keyboards/unix60/ /Users/andy/qmk_firmware/keyboards/fr4/unix60/keymaps/teknostatik/
	rsync -avz /Users/andy/Dropbox/Scripts/github/keyboards/ferris_sweep_mechboards/ /Users/andy/qmk_firmware/keyboards/ferris/keymaps/teknostatik_mb/
	rsync -avz /Users/andy/Dropbox/Scripts/github/keyboards/ferris_sweep/ /Users/andy/qmk_firmware/keyboards/ferris/keymaps/teknostatik/
	rsync -avz /Users/andy/Dropbox/Scripts/github/keyboards/cantor/ /Users/andy/qmk_firmware/keyboards/cantor/keymaps/teknostatik/
	rsync -avz /Users/andy/Dropbox/Scripts/github/keyboards/tidbit/ /Users/andy/qmk_firmware/keyboards/nullbitsco/tidbit/keymaps/teknostatik
	rsync -avz /Users/andy/Dropbox/Scripts/github/keyboards/ok60/ /Users/andy/qmk_firmware/keyboards/ok60/keymaps/teknostatik/
	rsync -avz /Users/andy/Dropbox/Scripts/github/keyboards/planck_rev7/ /Users/andy/qmk_firmware/keyboards/planck/rev7/keymaps/teknostatik7
else
	echo "Dropbox not detected; skipping QMK sync."
fi

if command -v nix >/dev/null 2>&1; then
	echo "Nix detected; updating packages and collecting garbage."
	nix-channel --update
	nix-env -u
	nix-collect-garbage -d
else
	echo "Nix not detected; skipping Nix update and garbage collection."
fi

echo "The script has now finished running."
